import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'id';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    nav_features: 'Features',
    nav_pricing: 'Pricing',
    nav_about: 'About Us',
    nav_interview: 'InterviewMate',
    nav_login: 'Login',
    nav_signup: 'Sign Up',
    hero_badge: '“LULUSKERJA!” #Noribet-ribet',
    hero_title: 'Navigate Your Career, End to End',
    hero_subtitle: 'An End-to-End AI Career Navigation Ecosystem for Indonesian Students & Fresh Graduates.',
    hero_description: 'CareerMate guides job seekers from preparing ATS-ready documents and practicing interviews for a target company to finding roles that match their interests and strengths.',
    hero_cta: 'Start Building Your Future for Free',
    problem_label: 'The Data',
    problem_title: 'The Challenge Graduates Face',
    problem_description: 'Indonesian graduates enter an increasingly competitive market while automated selection and skill mismatch make their first career step harder.',
    problem_stat_1_title: '109 applicants for one internship',
    problem_stat_1_desc: 'Average internship competition has nearly doubled year over year (Kelly Services, 2025).',
    problem_stat_2_title: '75% of CVs are filtered by ATS',
    problem_stat_2_desc: 'Applications can fail automated screening before a human recruiter reads them.',
    problem_stat_3_title: '8 million graduates face skill mismatch',
    problem_stat_3_desc: 'Many graduates work below or outside their qualifications (LPEM FEB UI, 2026).',
    problem_stat_4_title: '1.03 million graduates are unemployed',
    problem_stat_4_desc: 'Graduate unemployment reached 6.09%, above the 4.65% national rate (BPS Sakernas, May 2026).',
    solution_label: 'The Solution',
    solution_title: 'Your Complete Career Solution',
    solution_description: 'CareerMate brings preparation, practice, matching, and document management into one connected journey.',
    solution_item_1: 'ATS-ready AI CV & motivation letter builder with contextual microlearning',
    solution_item_2: 'Company-specific interview simulations with professional HR mentor validation',
    solution_item_3: 'Job matching based on interests and strengths, not keywords alone',
    solution_item_4: 'An integrated journey from preparation through job placement',
    features_title: 'Powerful Features to Accelerate Your Career',
    cvmate_title: 'CVMate',
    cvmate_description: 'AI-powered CV and resume builder with ATS optimization and professional templates',
    jobmate_title: 'JobMate',
    jobmate_description: 'Smart job matching platform that connects you with opportunities tailored to your profile',
    interviewmate_title: 'InterviewMate',
    interviewmate_description: 'AI interview simulator to practice and improve with role-specific feedback',
    documate_title: 'DocuMate',
    documate_description: 'A concise archive of your CV reviews, stored privately in this browser',
    insightmate_title: 'InsightMate',
    insightmate_description: 'Industry skill signals and career taxonomy insights from the CareerMate backend',
    feature_dashboard_preview: 'Dashboard preview',
    pricing_title: 'Simple, Transparent Pricing',
    pricing_free: 'Free',
    pricing_medium: 'Medium',
    pricing_premium: 'Premium',
    pricing_free_price: 'Rp 0',
    pricing_medium_price: 'Rp 35,000',
    pricing_premium_price: 'Rp 69,000',
    pricing_per_month: '/month',
    pricing_cta_free: 'Get Started',
    pricing_cta_medium: 'Choose Medium',
    pricing_cta_premium: 'Upgrade Now',
    pricing_popular: 'Most Popular',
    pricing_free_feature_1: 'Basic ATS CV templates',
    pricing_free_feature_2: 'Initial ATS score',
    pricing_free_feature_3: '3 interview practice sessions/month',
    pricing_free_feature_4: 'Basic job listing access',
    pricing_medium_feature_1: 'Full ATS templates & in-depth review',
    pricing_medium_feature_2: 'Missing ATS keyword analysis',
    pricing_medium_feature_3: '15 AI interview simulations/month',
    pricing_medium_feature_4: 'Personalized company & role scenarios',
    pricing_medium_feature_5: 'Complete contextual microlearning',
    pricing_premium_feature_1: 'All Medium features',
    pricing_premium_feature_2: 'Unlimited AI interview simulations',
    pricing_premium_feature_3: 'Two-stage validation by a professional HR mentor',
    pricing_premium_feature_4: 'Priority job-match gap analysis',
    pricing_premium_feature_5: 'Unlimited document archive',
    pricing_token_title: 'Prefer not to subscribe monthly?',
    pricing_token_desc: 'Buy flexible tokens from Rp 10,000 for one interview simulation or one in-depth review.',
    pricing_token_badge: 'Pay per use',
    testimonials_title: 'Success Stories from Our Users',
    cta_title: 'Ready to Launch Your Career?',
    cta_description: 'Join thousands of Indonesian professionals who are building their dream careers with CareerMate',
    cta_button: 'Start Your Free Account',
    footer_tagline: 'Your trusted career companion',
    footer_product: 'Product',
    footer_company: 'Company',
    footer_support: 'Support',
    footer_legal: 'Legal',
    cvmate_hero_title: 'Create Professional CVs that Pass ATS Screening in Minutes',
    cvmate_hero_subtitle: 'With CVMate\'s AI technology, transform your experience into CVs that attract recruiters and are optimized for Applicant Tracking Systems (ATS).',
    cvmate_hero_cta: 'Try CVMate for Free',
    cvmate_why_title: 'Why CVMate?',
    cvmate_ats_title: 'Pass ATS Screening',
    cvmate_ats_desc: 'CVMate helps create ATS-friendly CVs that get through automated screening systems.',
    cvmate_design_title: 'Professional & Creative Design',
    cvmate_design_desc: 'Choose between ATS-safe templates or more creative designs that stand out.',
    cvmate_ai_title: 'AI-Powered Guidance',
    cvmate_ai_desc: 'Get keyword suggestions and content guidance to present your best information.',
    cvmate_analytics_title: 'Advanced Analytics',
    cvmate_analytics_desc: 'Premium feature to measure your CV\'s effectiveness with detailed insights.',
    cvmate_demo_title: 'See CVMate in Action',
    cvmate_demo_subtitle: 'Interactive editor with AI-powered suggestions',
    cvmate_score_label: 'CV Strength Score',
    cvmate_templates_title: 'Choose Your Perfect Template',
    cvmate_templates_subtitle: 'Professional designs optimized for your success',
    cvmate_before_after_title: 'The CVMate Difference',
    cvmate_before_label: 'Before',
    cvmate_after_label: 'After',
    cvmate_final_cta_title: 'Ready to Start Your Dream Career?',
    cvmate_final_cta_desc: 'Create a professional CV in minutes with CVMate\'s AI-powered builder. Start for free today.',
    cvmate_final_cta_button: 'Create Your Professional CV Now',
  },
  id: {
    nav_features: 'Fitur',
    nav_pricing: 'Harga',
    nav_about: 'Tentang Kami',
    nav_interview: 'InterviewMate',
    nav_login: 'Masuk',
    nav_signup: 'Daftar',
    hero_badge: '“LULUSKERJA!” #Noribet-ribet',
    hero_title: 'Navigasi Karier, dari Lulus sampai Kerja',
    hero_subtitle: 'Ekosistem AI Navigasi Karier End-to-End untuk Mahasiswa & Fresh Graduate Indonesia.',
    hero_description: 'CareerMate mendampingi pencari kerja mulai dari persiapan berkas ramah ATS, simulasi wawancara sesuai perusahaan tujuan, hingga menemukan pekerjaan yang cocok dengan minat dan kekuatan diri.',
    hero_cta: 'Mulai Bangun Masa Depan Anda Gratis',
    problem_label: 'Data Masalah',
    problem_title: 'Tantangan yang Dihadapi Lulusan',
    problem_description: 'Lulusan Indonesia memasuki pasar yang makin kompetitif, sementara seleksi otomatis dan skill mismatch mempersulit langkah pertama karier mereka.',
    problem_stat_1_title: '1 lowongan diperebutkan 109 pelamar',
    problem_stat_1_desc: 'Rata-rata persaingan pelamar magang hampir dua kali lipat dibanding tahun sebelumnya (Kelly Services, 2025).',
    problem_stat_2_title: '75% CV tersaring otomatis oleh ATS',
    problem_stat_2_desc: 'CV dapat gugur pada seleksi otomatis sebelum sempat dibaca oleh rekruter manusia.',
    problem_stat_3_title: '8 juta sarjana mengalami skill mismatch',
    problem_stat_3_desc: 'Banyak sarjana bekerja tidak sesuai atau di bawah kualifikasinya (LPEM FEB UI, 2026).',
    problem_stat_4_title: '1,03 juta sarjana menganggur',
    problem_stat_4_desc: 'TPT sarjana mencapai 6,09%, di atas rata-rata nasional 4,65% (BPS Sakernas, Mei 2026).',
    solution_label: 'Solusi CareerMate',
    solution_title: 'Solusi Karier Lengkap Anda',
    solution_description: 'CareerMate menyatukan persiapan, latihan, pencocokan, dan pengelolaan dokumen dalam satu perjalanan terhubung.',
    solution_item_1: 'AI CV & MotLet Builder ramah ATS dengan microlearning kontekstual',
    solution_item_2: 'Simulasi wawancara per perusahaan dengan validasi mentor HR profesional',
    solution_item_3: 'Job matching berbasis minat dan bakat, bukan sekadar kata kunci',
    solution_item_4: 'Perjalanan terintegrasi dari persiapan hingga penempatan kerja',
    features_title: 'Fitur Powerful untuk Mempercepat Karier Anda',
    cvmate_title: 'CVMate',
    cvmate_description: 'Pembuat CV bertenaga AI dengan optimasi ATS dan template profesional',
    jobmate_title: 'JobMate',
    jobmate_description: 'Platform pencarian kerja pintar yang menghubungkan Anda dengan peluang sesuai profil',
    interviewmate_title: 'InterviewMate',
    interviewmate_description: 'Simulator wawancara AI dengan latihan dan umpan balik sesuai posisi target',
    documate_title: 'DocuMate',
    documate_description: 'Arsip ringkas hasil review CV yang disimpan secara privat di browser ini',
    insightmate_title: 'InsightMate',
    insightmate_description: 'Sinyal skill industri dan wawasan taksonomi karier dari backend CareerMate',
    feature_dashboard_preview: 'Preview di Dashboard',
    pricing_title: 'Harga yang Sederhana dan Transparan',
    pricing_free: 'Gratis',
    pricing_medium: 'Medium',
    pricing_premium: 'Premium',
    pricing_free_price: 'Rp 0',
    pricing_medium_price: 'Rp 35.000',
    pricing_premium_price: 'Rp 69.000',
    pricing_per_month: '/bulan',
    pricing_cta_free: 'Mulai Sekarang',
    pricing_cta_medium: 'Pilih Medium',
    pricing_cta_premium: 'Upgrade Sekarang',
    pricing_popular: 'Paling Populer',
    pricing_free_feature_1: 'Template CV ATS dasar',
    pricing_free_feature_2: 'Skor ATS awal',
    pricing_free_feature_3: '3 sesi latihan wawancara/bulan',
    pricing_free_feature_4: 'Akses lowongan pekerjaan dasar',
    pricing_medium_feature_1: 'Akses penuh template ATS & review mendalam',
    pricing_medium_feature_2: 'Analisis kata kunci ATS yang hilang',
    pricing_medium_feature_3: '15 simulasi wawancara AI/bulan',
    pricing_medium_feature_4: 'Skenario personal per perusahaan & posisi',
    pricing_medium_feature_5: 'Microlearning kontekstual lengkap',
    pricing_premium_feature_1: 'Seluruh fitur Medium',
    pricing_premium_feature_2: 'Simulasi wawancara AI tanpa batas',
    pricing_premium_feature_3: 'Validasi 2 tahap oleh mentor HR profesional',
    pricing_premium_feature_4: 'Job Match Gap Analysis prioritas',
    pricing_premium_feature_5: 'Penyimpanan arsip dokumen tanpa batas',
    pricing_token_title: 'Tidak ingin langganan bulanan?',
    pricing_token_desc: 'Beli token fleksibel mulai Rp 10.000 untuk 1x simulasi interview atau 1x review mendalam.',
    pricing_token_badge: 'Bayar sesuai pemakaian',
    testimonials_title: 'Kisah Sukses dari Pengguna Kami',
    cta_title: 'Siap Meluncurkan Karier Anda?',
    cta_description: 'Bergabunglah dengan ribuan profesional Indonesia yang membangun karier impian mereka dengan CareerMate',
    cta_button: 'Buat Akun Gratis',
    footer_tagline: 'Pendamping karier terpercaya Anda',
    footer_product: 'Produk',
    footer_company: 'Perusahaan',
    footer_support: 'Dukungan',
    footer_legal: 'Legal',
    cvmate_hero_title: 'Buat CV Profesional yang Lolos Seleksi ATS dalam Hitungan Menit',
    cvmate_hero_subtitle: 'Dengan teknologi AI dari CVMate, ubah pengalaman Anda menjadi CV yang menarik perhatian perekrut dan dioptimalkan untuk sistem pelacakan pelamar (ATS).',
    cvmate_hero_cta: 'Coba CVMate Gratis',
    cvmate_why_title: 'Mengapa CVMate?',
    cvmate_ats_title: 'Lolos Seleksi ATS',
    cvmate_ats_desc: 'CVMate membantu membuat CV yang ATS-friendly agar lolos sistem seleksi otomatis.',
    cvmate_design_title: 'Desain Profesional & Kreatif',
    cvmate_design_desc: 'Pilih antara templat yang aman untuk ATS atau yang lebih kreatif untuk menonjol.',
    cvmate_ai_title: 'Panduan Berbasis AI',
    cvmate_ai_desc: 'Dapatkan saran kata kunci dan panduan isian untuk menyajikan informasi terbaik Anda.',
    cvmate_analytics_title: 'Analitik Tingkat Lanjut',
    cvmate_analytics_desc: 'Fitur premium untuk mengukur efektivitas CV Anda dengan wawasan mendalam.',
    cvmate_demo_title: 'Lihat CVMate Beraksi',
    cvmate_demo_subtitle: 'Editor interaktif dengan saran bertenaga AI',
    cvmate_score_label: 'Skor Kekuatan CV',
    cvmate_templates_title: 'Pilih Templat Sempurna Anda',
    cvmate_templates_subtitle: 'Desain profesional yang dioptimalkan untuk kesuksesan Anda',
    cvmate_before_after_title: 'Perbedaan dengan CVMate',
    cvmate_before_label: 'Sebelum',
    cvmate_after_label: 'Sesudah',
    cvmate_final_cta_title: 'Siap Memulai Karier Impian Anda?',
    cvmate_final_cta_desc: 'Buat CV profesional dalam hitungan menit dengan pembuat CV bertenaga AI CVMate. Mulai gratis hari ini.',
    cvmate_final_cta_button: 'Buat CV Profesional Anda Sekarang',
  },
} as const;

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const stored = localStorage.getItem('language') as Language;
    return stored === 'en' || stored === 'id' ? stored : 'id';
  });

  const toggleLanguage = () => {
    const newLang = language === 'en' ? 'id' : 'en';
    setLanguage(newLang);
    localStorage.setItem('language', newLang);
  };

  const t = (key: string): string => translations[language][key as keyof typeof translations.en] || key;

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
